# WHY: Centralised synonym dictionaries so the parser is data-driven, not hardcoded.
# To support a new section name, add one line here — no code changes needed.

SECTION_MAPPING = {
    # ── experience ──
    "experience": "experience",
    "work experience": "experience",
    "professional experience": "experience",
    "employment": "experience",
    "employment history": "experience",
    "internships": "experience",
    "internship": "experience",
    "work history": "experience",
    # ── education ──
    "education": "education",
    "academic background": "education",
    "qualifications": "education",
    "academic qualifications": "education",
    # ── skills ──
    "skills": "skills",
    "technical skills": "skills",
    "skills & tools": "skills",
    "skills and tools": "skills",
    "technologies": "skills",
    "core competencies": "skills",
    "technical competencies": "skills",
    # ── projects (kept aside; NEVER mapped to experience) ──
    "projects": "projects",
    "personal projects": "projects",
    "academic projects": "projects",
    # ── sections we recognise but never feed into experience/education ──
    "summary": "summary",
    "professional summary": "summary",
    "objective": "summary",
    "career objective": "summary",
    "about me": "summary",
    "achievements": "achievements",
    "awards": "achievements",
    "honors": "achievements",
    "honours": "achievements",
    "certifications": "certifications",
    "certificates": "certifications",
    "publications": "publications",
    "references": "references",
    "extracurricular": "extracurricular",
    "extracurricular activities": "extracurricular",
    "hobbies": "hobbies",
    "interests": "hobbies",
    "languages": "languages",
    "volunteer": "volunteer",
    "volunteer experience": "volunteer",
}

# WHY: Canonical casing map.  Keys are lowercase; values are the display form.
# Unknown skills are kept verbatim (title-cased) at lower confidence.
SKILL_ALIASES = {
    # ── languages ──
    "c++": "C++",
    "c plus plus": "C++",
    "c": "C",
    "c#": "C#",
    "c sharp": "C#",
    "java": "Java",
    "python": "Python",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "ruby": "Ruby",
    "php": "PHP",
    "r": "R",
    "scala": "Scala",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "dart": "Dart",
    "perl": "Perl",
    "shell": "Shell",
    "bash": "Bash",
    # ── frontend ──
    "html": "HTML",
    "html5": "HTML",
    "css": "CSS",
    "css3": "CSS",
    "react": "React",
    "react.js": "React",
    "reactjs": "React",
    "angular": "Angular",
    "angular.js": "Angular",
    "vue": "Vue",
    "vue.js": "Vue",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "svelte": "Svelte",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    # ── backend / frameworks ──
    "node": "Node.js",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "express": "Express",
    "express.js": "Express",
    "fastapi": "FastAPI",
    "flask": "Flask",
    "django": "Django",
    "spring": "Spring",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "rails": "Ruby on Rails",
    "ruby on rails": "Ruby on Rails",
    "rest apis": "REST APIs",
    "rest api": "REST APIs",
    "restful": "REST APIs",
    "graphql": "GraphQL",
    # ── databases ──
    "sql": "SQL",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "sqlite": "SQLite",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",
    "elasticsearch": "Elasticsearch",
    # ── cloud / infra ──
    "aws": "AWS",
    "amazon web services": "AWS",
    "gcp": "Google Cloud",
    "google cloud": "Google Cloud",
    "google cloud platform": "Google Cloud",
    "azure": "Azure",
    "microsoft azure": "Azure",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "ci/cd": "CI/CD",
    "github actions": "GitHub Actions",
    # ── data / ML ──
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scipy": "SciPy",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "excel": "Excel",
    "matplotlib": "Matplotlib",
    # ── tools / misc ──
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "jira": "Jira",
    "linux": "Linux",
    "unix": "Unix",
    "kafka": "Kafka",
    "rabbitmq": "RabbitMQ",
    "nginx": "Nginx",
    "apache": "Apache",
    "siem": "SIEM",
    "splunk": "Splunk",
    "wireshark": "Wireshark",
    "burp suite": "Burp Suite",
    "nmap": "Nmap",
    "metasploit": "Metasploit",
    "figma": "Figma",
    "postman": "Postman",
}
